// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: mismatch_audit.
// - Entity ID: 102019b5ce6740972e199eb99a5c75dbabe.
// - Entity Version: 102019b5ff7ffb3702a8d716f62d21a3db0.
// - Task ID: 694fdd1627bf6305174669ec.
// - Task Root ID: 694f132f5296c90e87490c67.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for MismatchAuditModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface MismatchAuditModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  audit_date: string;
  old_behavior: string;
  labels: string;
  corrective_action: string;
}

/**
 * ORM class for MismatchAudit entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class MismatchAuditORM {
  private static instance: MismatchAuditORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b5ce6740972e199eb99a5c75dbabe';
    this.entityName = 'mismatch_audit';
    this.entityVersion = '102019b5ff7ffb3702a8d716f62d21a3db0';
    this.taskId = '694fdd1627bf6305174669ec';
    this.taskRootId = '694f132f5296c90e87490c67';
  }

  /**
   * Get singleton instance of MismatchAuditORM
   */
  public static getInstance(): MismatchAuditORM {
    if (!MismatchAuditORM.instance) {
      MismatchAuditORM.instance = new MismatchAuditORM();
    }
    
    return MismatchAuditORM.instance;
  }

  /**
   * Get mismatch_audit by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getMismatchAuditByIDs(ids: string[]): Promise<MismatchAuditModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete mismatch_audit by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteMismatchAuditByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all MismatchAudit records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllMismatchAudit(): Promise<MismatchAuditModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new MismatchAudit record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertMismatchAudit(data: MismatchAuditModel[]): Promise<MismatchAuditModel[]> {
    const structured = data.map((item) => CreateData(MismatchAuditModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all MismatchAudit records
   */
  async purgeAllMismatchAudit(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List MismatchAudit records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listMismatchAudit(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[MismatchAuditModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get mismatch_audit by Id index
   * This function gets data by index.
   */
  async getMismatchAuditById(
    id: string,
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) mismatch_audit by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMismatchAuditById(
    id: string,
    data: MismatchAuditModel
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexId(
      id
    );

    const values = MismatchAuditModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete mismatch_audit by Id index
   */
  async deleteMismatchAuditById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get mismatch_audit by DataCreator index
   * This function gets data by index.
   */
  async getMismatchAuditByDataCreator(
    data_creator: string,
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) mismatch_audit by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMismatchAuditByDataCreator(
    data_creator: string,
    data: MismatchAuditModel
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = MismatchAuditModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete mismatch_audit by DataCreator index
   */
  async deleteMismatchAuditByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get mismatch_audit by DataUpdater index
   * This function gets data by index.
   */
  async getMismatchAuditByDataUpdater(
    data_updater: string,
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) mismatch_audit by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMismatchAuditByDataUpdater(
    data_updater: string,
    data: MismatchAuditModel
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = MismatchAuditModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete mismatch_audit by DataUpdater index
   */
  async deleteMismatchAuditByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get mismatch_audit by UserId index
   * This function gets data by index.
   */
  async getMismatchAuditByUserId(
    user_id: string,
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) mismatch_audit by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMismatchAuditByUserId(
    user_id: string,
    data: MismatchAuditModel
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = MismatchAuditModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete mismatch_audit by UserId index
   */
  async deleteMismatchAuditByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get mismatch_audit by AuditDate index
   * This function gets data by index.
   */
  async getMismatchAuditByAuditDate(
    audit_date: string,
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexAuditDate(
      audit_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) mismatch_audit by AuditDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMismatchAuditByAuditDate(
    audit_date: string,
    data: MismatchAuditModel
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexAuditDate(
      audit_date
    );

    const values = MismatchAuditModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete mismatch_audit by AuditDate index
   */
  async deleteMismatchAuditByAuditDate(
    audit_date: string
  ): Promise<void> {
    const index = createIndexAuditDate(
      audit_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get mismatch_audit by AuditDateUserId index
   * This function gets data by index.
   */
  async getMismatchAuditByAuditDateUserId(
    audit_date: string,
    user_id: string,
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexAuditDateUserId(
      audit_date,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) mismatch_audit by AuditDateUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMismatchAuditByAuditDateUserId(
    audit_date: string,
    user_id: string,
    data: MismatchAuditModel
  ): Promise<MismatchAuditModel[]> {
    const index = createIndexAuditDateUserId(
      audit_date,
      user_id
    );

    const values = MismatchAuditModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete mismatch_audit by AuditDateUserId index
   */
  async deleteMismatchAuditByAuditDateUserId(
    audit_date: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexAuditDateUserId(
      audit_date,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to MismatchAuditModel data array
   */
  private resultToData(values: Data[]): MismatchAuditModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return MismatchAuditModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as MismatchAuditModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized MismatchAuditModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is MismatchAuditModel => item !== null);
  }
}

/**
 * Convert MismatchAuditModel data to Value array
 */
function MismatchAuditModelToValues(data: MismatchAuditModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'audit_date', type: DataType.string, defaultValue: '' },
    { key: 'old_behavior', type: DataType.string, defaultValue: '' },
    { key: 'labels', type: DataType.string, defaultValue: '' },
    { key: 'corrective_action', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof MismatchAuditModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to MismatchAuditModel data
 */
function MismatchAuditModelFromValues(values: Value[]): MismatchAuditModel {
  const data: Partial<MismatchAuditModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'audit_date':
        data.audit_date = ParseValue(value, DataType.string) as string;
        break;
      case 'old_behavior':
        data.old_behavior = ParseValue(value, DataType.string) as string;
        break;
      case 'labels':
        data.labels = ParseValue(value, DataType.string) as string;
        break;
      case 'corrective_action':
        data.corrective_action = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as MismatchAuditModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for AuditDate fields
 */
function createIndexAuditDate(
  audit_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, audit_date, 'audit_date'),
  ];

  return {
    fields: ['audit_date'],
    values
  };
}
/**
 * Create index for AuditDateUserId fields
 */
function createIndexAuditDateUserId(
  audit_date: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, audit_date, 'audit_date'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['audit_date', 'user_id'],
    values
  };
}

export default MismatchAuditORM;