// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_profile.
// - Entity ID: 102019b5ce6740976a6803a36d9abfaa04e.
// - Entity Version: 102019b5ff7ffb3702a8d716f62d21a3db0.
// - Task ID: 694fdd1627bf6305174669ec.
// - Task Root ID: 694f132f5296c90e87490c67.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for UserProfileModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserProfileModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  core_identity_statement: string;
  program_start_date: string;
  current_week: number;
  current_phase: number;
}

/**
 * ORM class for UserProfile entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserProfileORM {
  private static instance: UserProfileORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b5ce6740976a6803a36d9abfaa04e';
    this.entityName = 'user_profile';
    this.entityVersion = '102019b5ff7ffb3702a8d716f62d21a3db0';
    this.taskId = '694fdd1627bf6305174669ec';
    this.taskRootId = '694f132f5296c90e87490c67';
  }

  /**
   * Get singleton instance of UserProfileORM
   */
  public static getInstance(): UserProfileORM {
    if (!UserProfileORM.instance) {
      UserProfileORM.instance = new UserProfileORM();
    }
    
    return UserProfileORM.instance;
  }

  /**
   * Get user_profile by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getUserProfileByIDs(ids: string[]): Promise<UserProfileModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteUserProfileByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all UserProfile records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserProfile(): Promise<UserProfileModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserProfile record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserProfile(data: UserProfileModel[]): Promise<UserProfileModel[]> {
    const structured = data.map((item) => CreateData(UserProfileModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserProfile records
   */
  async purgeAllUserProfile(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserProfile records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserProfile(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserProfileModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_profile by Id index
   * This function gets data by index.
   */
  async getUserProfileById(
    id: string,
  ): Promise<UserProfileModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileById(
    id: string,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by Id index
   */
  async deleteUserProfileById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_profile by DataCreator index
   * This function gets data by index.
   */
  async getUserProfileByDataCreator(
    data_creator: string,
  ): Promise<UserProfileModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileByDataCreator(
    data_creator: string,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by DataCreator index
   */
  async deleteUserProfileByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_profile by DataUpdater index
   * This function gets data by index.
   */
  async getUserProfileByDataUpdater(
    data_updater: string,
  ): Promise<UserProfileModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileByDataUpdater(
    data_updater: string,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by DataUpdater index
   */
  async deleteUserProfileByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_profile by UserId index
   * This function gets data by index.
   */
  async getUserProfileByUserId(
    user_id: string,
  ): Promise<UserProfileModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileByUserId(
    user_id: string,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by UserId index
   */
  async deleteUserProfileByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_profile by CurrentWeek index
   * This function gets data by index.
   */
  async getUserProfileByCurrentWeek(
    current_week: number,
  ): Promise<UserProfileModel[]> {
    const index = createIndexCurrentWeek(
      current_week
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by CurrentWeek index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileByCurrentWeek(
    current_week: number,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexCurrentWeek(
      current_week
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by CurrentWeek index
   */
  async deleteUserProfileByCurrentWeek(
    current_week: number
  ): Promise<void> {
    const index = createIndexCurrentWeek(
      current_week
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_profile by CurrentPhase index
   * This function gets data by index.
   */
  async getUserProfileByCurrentPhase(
    current_phase: number,
  ): Promise<UserProfileModel[]> {
    const index = createIndexCurrentPhase(
      current_phase
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by CurrentPhase index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileByCurrentPhase(
    current_phase: number,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexCurrentPhase(
      current_phase
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by CurrentPhase index
   */
  async deleteUserProfileByCurrentPhase(
    current_phase: number
  ): Promise<void> {
    const index = createIndexCurrentPhase(
      current_phase
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserProfileModel data array
   */
  private resultToData(values: Data[]): UserProfileModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserProfileModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserProfileModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserProfileModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserProfileModel => item !== null);
  }
}

/**
 * Convert UserProfileModel data to Value array
 */
function UserProfileModelToValues(data: UserProfileModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'core_identity_statement', type: DataType.string, defaultValue: '' },
    { key: 'program_start_date', type: DataType.string, defaultValue: '' },
    { key: 'current_week', type: DataType.number, defaultValue: 0 },
    { key: 'current_phase', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserProfileModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserProfileModel data
 */
function UserProfileModelFromValues(values: Value[]): UserProfileModel {
  const data: Partial<UserProfileModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'core_identity_statement':
        data.core_identity_statement = ParseValue(value, DataType.string) as string;
        break;
      case 'program_start_date':
        data.program_start_date = ParseValue(value, DataType.string) as string;
        break;
      case 'current_week':
        data.current_week = ParseValue(value, DataType.number) as number;
        break;
      case 'current_phase':
        data.current_phase = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as UserProfileModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for CurrentWeek fields
 */
function createIndexCurrentWeek(
  current_week: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, current_week, 'current_week'),
  ];

  return {
    fields: ['current_week'],
    values
  };
}
/**
 * Create index for CurrentPhase fields
 */
function createIndexCurrentPhase(
  current_phase: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, current_phase, 'current_phase'),
  ];

  return {
    fields: ['current_phase'],
    values
  };
}

export default UserProfileORM;