// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: final_week_document.
// - Entity ID: 102019b5ce674087e789a67901570695d1f.
// - Entity Version: 102019b5ff7ffb3702a8d716f62d21a3db0.
// - Task ID: 694fdd1627bf6305174669ec.
// - Task Root ID: 694f132f5296c90e87490c67.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for FinalWeekDocumentModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface FinalWeekDocumentModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  document: string;
  completed_date: string;
}

/**
 * ORM class for FinalWeekDocument entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class FinalWeekDocumentORM {
  private static instance: FinalWeekDocumentORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b5ce674087e789a67901570695d1f';
    this.entityName = 'final_week_document';
    this.entityVersion = '102019b5ff7ffb3702a8d716f62d21a3db0';
    this.taskId = '694fdd1627bf6305174669ec';
    this.taskRootId = '694f132f5296c90e87490c67';
  }

  /**
   * Get singleton instance of FinalWeekDocumentORM
   */
  public static getInstance(): FinalWeekDocumentORM {
    if (!FinalWeekDocumentORM.instance) {
      FinalWeekDocumentORM.instance = new FinalWeekDocumentORM();
    }
    
    return FinalWeekDocumentORM.instance;
  }

  /**
   * Get final_week_document by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getFinalWeekDocumentByIDs(ids: string[]): Promise<FinalWeekDocumentModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete final_week_document by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteFinalWeekDocumentByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all FinalWeekDocument records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllFinalWeekDocument(): Promise<FinalWeekDocumentModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new FinalWeekDocument record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertFinalWeekDocument(data: FinalWeekDocumentModel[]): Promise<FinalWeekDocumentModel[]> {
    const structured = data.map((item) => CreateData(FinalWeekDocumentModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all FinalWeekDocument records
   */
  async purgeAllFinalWeekDocument(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List FinalWeekDocument records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listFinalWeekDocument(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[FinalWeekDocumentModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get final_week_document by Id index
   * This function gets data by index.
   */
  async getFinalWeekDocumentById(
    id: string,
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) final_week_document by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinalWeekDocumentById(
    id: string,
    data: FinalWeekDocumentModel
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexId(
      id
    );

    const values = FinalWeekDocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete final_week_document by Id index
   */
  async deleteFinalWeekDocumentById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get final_week_document by DataCreator index
   * This function gets data by index.
   */
  async getFinalWeekDocumentByDataCreator(
    data_creator: string,
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) final_week_document by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinalWeekDocumentByDataCreator(
    data_creator: string,
    data: FinalWeekDocumentModel
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = FinalWeekDocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete final_week_document by DataCreator index
   */
  async deleteFinalWeekDocumentByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get final_week_document by DataUpdater index
   * This function gets data by index.
   */
  async getFinalWeekDocumentByDataUpdater(
    data_updater: string,
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) final_week_document by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinalWeekDocumentByDataUpdater(
    data_updater: string,
    data: FinalWeekDocumentModel
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = FinalWeekDocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete final_week_document by DataUpdater index
   */
  async deleteFinalWeekDocumentByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get final_week_document by UserId index
   * This function gets data by index.
   */
  async getFinalWeekDocumentByUserId(
    user_id: string,
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) final_week_document by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinalWeekDocumentByUserId(
    user_id: string,
    data: FinalWeekDocumentModel
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = FinalWeekDocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete final_week_document by UserId index
   */
  async deleteFinalWeekDocumentByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get final_week_document by CompletedDate index
   * This function gets data by index.
   */
  async getFinalWeekDocumentByCompletedDate(
    completed_date: string,
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexCompletedDate(
      completed_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) final_week_document by CompletedDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinalWeekDocumentByCompletedDate(
    completed_date: string,
    data: FinalWeekDocumentModel
  ): Promise<FinalWeekDocumentModel[]> {
    const index = createIndexCompletedDate(
      completed_date
    );

    const values = FinalWeekDocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete final_week_document by CompletedDate index
   */
  async deleteFinalWeekDocumentByCompletedDate(
    completed_date: string
  ): Promise<void> {
    const index = createIndexCompletedDate(
      completed_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to FinalWeekDocumentModel data array
   */
  private resultToData(values: Data[]): FinalWeekDocumentModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return FinalWeekDocumentModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as FinalWeekDocumentModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized FinalWeekDocumentModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is FinalWeekDocumentModel => item !== null);
  }
}

/**
 * Convert FinalWeekDocumentModel data to Value array
 */
function FinalWeekDocumentModelToValues(data: FinalWeekDocumentModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'document', type: DataType.string, defaultValue: '' },
    { key: 'completed_date', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof FinalWeekDocumentModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to FinalWeekDocumentModel data
 */
function FinalWeekDocumentModelFromValues(values: Value[]): FinalWeekDocumentModel {
  const data: Partial<FinalWeekDocumentModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'document':
        data.document = ParseValue(value, DataType.string) as string;
        break;
      case 'completed_date':
        data.completed_date = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as FinalWeekDocumentModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for CompletedDate fields
 */
function createIndexCompletedDate(
  completed_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, completed_date, 'completed_date'),
  ];

  return {
    fields: ['completed_date'],
    values
  };
}

export default FinalWeekDocumentORM;