// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: body_protocol_workout.
// - Entity ID: 102019b5ce67409741eb8b221a893ac1d09.
// - Entity Version: 102019b5ff7ffb3702a8d716f62d21a3db0.
// - Task ID: 694fdd1627bf6305174669ec.
// - Task Root ID: 694f132f5296c90e87490c67.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for BodyProtocolWorkoutModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface BodyProtocolWorkoutModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  workout_date: string;
  phase: number;
  completed: boolean;
}

/**
 * ORM class for BodyProtocolWorkout entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class BodyProtocolWorkoutORM {
  private static instance: BodyProtocolWorkoutORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b5ce67409741eb8b221a893ac1d09';
    this.entityName = 'body_protocol_workout';
    this.entityVersion = '102019b5ff7ffb3702a8d716f62d21a3db0';
    this.taskId = '694fdd1627bf6305174669ec';
    this.taskRootId = '694f132f5296c90e87490c67';
  }

  /**
   * Get singleton instance of BodyProtocolWorkoutORM
   */
  public static getInstance(): BodyProtocolWorkoutORM {
    if (!BodyProtocolWorkoutORM.instance) {
      BodyProtocolWorkoutORM.instance = new BodyProtocolWorkoutORM();
    }
    
    return BodyProtocolWorkoutORM.instance;
  }

  /**
   * Get body_protocol_workout by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getBodyProtocolWorkoutByIDs(ids: string[]): Promise<BodyProtocolWorkoutModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete body_protocol_workout by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteBodyProtocolWorkoutByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all BodyProtocolWorkout records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllBodyProtocolWorkout(): Promise<BodyProtocolWorkoutModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new BodyProtocolWorkout record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertBodyProtocolWorkout(data: BodyProtocolWorkoutModel[]): Promise<BodyProtocolWorkoutModel[]> {
    const structured = data.map((item) => CreateData(BodyProtocolWorkoutModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all BodyProtocolWorkout records
   */
  async purgeAllBodyProtocolWorkout(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List BodyProtocolWorkout records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listBodyProtocolWorkout(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[BodyProtocolWorkoutModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get body_protocol_workout by Id index
   * This function gets data by index.
   */
  async getBodyProtocolWorkoutById(
    id: string,
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) body_protocol_workout by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBodyProtocolWorkoutById(
    id: string,
    data: BodyProtocolWorkoutModel
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexId(
      id
    );

    const values = BodyProtocolWorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete body_protocol_workout by Id index
   */
  async deleteBodyProtocolWorkoutById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get body_protocol_workout by DataCreator index
   * This function gets data by index.
   */
  async getBodyProtocolWorkoutByDataCreator(
    data_creator: string,
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) body_protocol_workout by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBodyProtocolWorkoutByDataCreator(
    data_creator: string,
    data: BodyProtocolWorkoutModel
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = BodyProtocolWorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete body_protocol_workout by DataCreator index
   */
  async deleteBodyProtocolWorkoutByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get body_protocol_workout by DataUpdater index
   * This function gets data by index.
   */
  async getBodyProtocolWorkoutByDataUpdater(
    data_updater: string,
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) body_protocol_workout by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBodyProtocolWorkoutByDataUpdater(
    data_updater: string,
    data: BodyProtocolWorkoutModel
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = BodyProtocolWorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete body_protocol_workout by DataUpdater index
   */
  async deleteBodyProtocolWorkoutByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get body_protocol_workout by UserId index
   * This function gets data by index.
   */
  async getBodyProtocolWorkoutByUserId(
    user_id: string,
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) body_protocol_workout by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBodyProtocolWorkoutByUserId(
    user_id: string,
    data: BodyProtocolWorkoutModel
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = BodyProtocolWorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete body_protocol_workout by UserId index
   */
  async deleteBodyProtocolWorkoutByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get body_protocol_workout by WorkoutDate index
   * This function gets data by index.
   */
  async getBodyProtocolWorkoutByWorkoutDate(
    workout_date: string,
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexWorkoutDate(
      workout_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) body_protocol_workout by WorkoutDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBodyProtocolWorkoutByWorkoutDate(
    workout_date: string,
    data: BodyProtocolWorkoutModel
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexWorkoutDate(
      workout_date
    );

    const values = BodyProtocolWorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete body_protocol_workout by WorkoutDate index
   */
  async deleteBodyProtocolWorkoutByWorkoutDate(
    workout_date: string
  ): Promise<void> {
    const index = createIndexWorkoutDate(
      workout_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get body_protocol_workout by UserIdWorkoutDate index
   * This function gets data by index.
   */
  async getBodyProtocolWorkoutByUserIdWorkoutDate(
    user_id: string,
    workout_date: string,
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexUserIdWorkoutDate(
      user_id,
      workout_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) body_protocol_workout by UserIdWorkoutDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBodyProtocolWorkoutByUserIdWorkoutDate(
    user_id: string,
    workout_date: string,
    data: BodyProtocolWorkoutModel
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexUserIdWorkoutDate(
      user_id,
      workout_date
    );

    const values = BodyProtocolWorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete body_protocol_workout by UserIdWorkoutDate index
   */
  async deleteBodyProtocolWorkoutByUserIdWorkoutDate(
    user_id: string,
    workout_date: string
  ): Promise<void> {
    const index = createIndexUserIdWorkoutDate(
      user_id,
      workout_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get body_protocol_workout by Phase index
   * This function gets data by index.
   */
  async getBodyProtocolWorkoutByPhase(
    phase: number,
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexPhase(
      phase
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) body_protocol_workout by Phase index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBodyProtocolWorkoutByPhase(
    phase: number,
    data: BodyProtocolWorkoutModel
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexPhase(
      phase
    );

    const values = BodyProtocolWorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete body_protocol_workout by Phase index
   */
  async deleteBodyProtocolWorkoutByPhase(
    phase: number
  ): Promise<void> {
    const index = createIndexPhase(
      phase
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get body_protocol_workout by PhaseUserId index
   * This function gets data by index.
   */
  async getBodyProtocolWorkoutByPhaseUserId(
    phase: number,
    user_id: string,
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexPhaseUserId(
      phase,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) body_protocol_workout by PhaseUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBodyProtocolWorkoutByPhaseUserId(
    phase: number,
    user_id: string,
    data: BodyProtocolWorkoutModel
  ): Promise<BodyProtocolWorkoutModel[]> {
    const index = createIndexPhaseUserId(
      phase,
      user_id
    );

    const values = BodyProtocolWorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete body_protocol_workout by PhaseUserId index
   */
  async deleteBodyProtocolWorkoutByPhaseUserId(
    phase: number,
    user_id: string
  ): Promise<void> {
    const index = createIndexPhaseUserId(
      phase,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to BodyProtocolWorkoutModel data array
   */
  private resultToData(values: Data[]): BodyProtocolWorkoutModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return BodyProtocolWorkoutModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as BodyProtocolWorkoutModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized BodyProtocolWorkoutModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is BodyProtocolWorkoutModel => item !== null);
  }
}

/**
 * Convert BodyProtocolWorkoutModel data to Value array
 */
function BodyProtocolWorkoutModelToValues(data: BodyProtocolWorkoutModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'workout_date', type: DataType.string, defaultValue: '' },
    { key: 'phase', type: DataType.number, defaultValue: 0 },
    { key: 'completed', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof BodyProtocolWorkoutModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to BodyProtocolWorkoutModel data
 */
function BodyProtocolWorkoutModelFromValues(values: Value[]): BodyProtocolWorkoutModel {
  const data: Partial<BodyProtocolWorkoutModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'workout_date':
        data.workout_date = ParseValue(value, DataType.string) as string;
        break;
      case 'phase':
        data.phase = ParseValue(value, DataType.number) as number;
        break;
      case 'completed':
        data.completed = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as BodyProtocolWorkoutModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for WorkoutDate fields
 */
function createIndexWorkoutDate(
  workout_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, workout_date, 'workout_date'),
  ];

  return {
    fields: ['workout_date'],
    values
  };
}
/**
 * Create index for UserIdWorkoutDate fields
 */
function createIndexUserIdWorkoutDate(
  user_id: string,
  workout_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
    CreateValue(DataType.string, workout_date, 'workout_date'),
  ];

  return {
    fields: ['user_id', 'workout_date'],
    values
  };
}
/**
 * Create index for Phase fields
 */
function createIndexPhase(
  phase: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, phase, 'phase'),
  ];

  return {
    fields: ['phase'],
    values
  };
}
/**
 * Create index for PhaseUserId fields
 */
function createIndexPhaseUserId(
  phase: number,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, phase, 'phase'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['phase', 'user_id'],
    values
  };
}

export default BodyProtocolWorkoutORM;