// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: microproof_evidence.
// - Entity ID: 102019b5ce67409793d8d2f9b104ad2c041.
// - Entity Version: 102019b5ff7ffb3702a8d716f62d21a3db0.
// - Task ID: 694fdd1627bf6305174669ec.
// - Task Root ID: 694f132f5296c90e87490c67.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for MicroproofEvidenceModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface MicroproofEvidenceModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  proof_date: string;
  evidence: string;
}

/**
 * ORM class for MicroproofEvidence entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class MicroproofEvidenceORM {
  private static instance: MicroproofEvidenceORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b5ce67409793d8d2f9b104ad2c041';
    this.entityName = 'microproof_evidence';
    this.entityVersion = '102019b5ff7ffb3702a8d716f62d21a3db0';
    this.taskId = '694fdd1627bf6305174669ec';
    this.taskRootId = '694f132f5296c90e87490c67';
  }

  /**
   * Get singleton instance of MicroproofEvidenceORM
   */
  public static getInstance(): MicroproofEvidenceORM {
    if (!MicroproofEvidenceORM.instance) {
      MicroproofEvidenceORM.instance = new MicroproofEvidenceORM();
    }
    
    return MicroproofEvidenceORM.instance;
  }

  /**
   * Get microproof_evidence by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getMicroproofEvidenceByIDs(ids: string[]): Promise<MicroproofEvidenceModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete microproof_evidence by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteMicroproofEvidenceByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all MicroproofEvidence records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllMicroproofEvidence(): Promise<MicroproofEvidenceModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new MicroproofEvidence record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertMicroproofEvidence(data: MicroproofEvidenceModel[]): Promise<MicroproofEvidenceModel[]> {
    const structured = data.map((item) => CreateData(MicroproofEvidenceModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all MicroproofEvidence records
   */
  async purgeAllMicroproofEvidence(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List MicroproofEvidence records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listMicroproofEvidence(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[MicroproofEvidenceModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get microproof_evidence by Id index
   * This function gets data by index.
   */
  async getMicroproofEvidenceById(
    id: string,
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) microproof_evidence by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMicroproofEvidenceById(
    id: string,
    data: MicroproofEvidenceModel
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexId(
      id
    );

    const values = MicroproofEvidenceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete microproof_evidence by Id index
   */
  async deleteMicroproofEvidenceById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get microproof_evidence by DataCreator index
   * This function gets data by index.
   */
  async getMicroproofEvidenceByDataCreator(
    data_creator: string,
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) microproof_evidence by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMicroproofEvidenceByDataCreator(
    data_creator: string,
    data: MicroproofEvidenceModel
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = MicroproofEvidenceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete microproof_evidence by DataCreator index
   */
  async deleteMicroproofEvidenceByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get microproof_evidence by DataUpdater index
   * This function gets data by index.
   */
  async getMicroproofEvidenceByDataUpdater(
    data_updater: string,
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) microproof_evidence by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMicroproofEvidenceByDataUpdater(
    data_updater: string,
    data: MicroproofEvidenceModel
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = MicroproofEvidenceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete microproof_evidence by DataUpdater index
   */
  async deleteMicroproofEvidenceByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get microproof_evidence by UserId index
   * This function gets data by index.
   */
  async getMicroproofEvidenceByUserId(
    user_id: string,
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) microproof_evidence by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMicroproofEvidenceByUserId(
    user_id: string,
    data: MicroproofEvidenceModel
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = MicroproofEvidenceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete microproof_evidence by UserId index
   */
  async deleteMicroproofEvidenceByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get microproof_evidence by ProofDate index
   * This function gets data by index.
   */
  async getMicroproofEvidenceByProofDate(
    proof_date: string,
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexProofDate(
      proof_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) microproof_evidence by ProofDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMicroproofEvidenceByProofDate(
    proof_date: string,
    data: MicroproofEvidenceModel
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexProofDate(
      proof_date
    );

    const values = MicroproofEvidenceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete microproof_evidence by ProofDate index
   */
  async deleteMicroproofEvidenceByProofDate(
    proof_date: string
  ): Promise<void> {
    const index = createIndexProofDate(
      proof_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get microproof_evidence by ProofDateUserId index
   * This function gets data by index.
   */
  async getMicroproofEvidenceByProofDateUserId(
    proof_date: string,
    user_id: string,
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexProofDateUserId(
      proof_date,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) microproof_evidence by ProofDateUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMicroproofEvidenceByProofDateUserId(
    proof_date: string,
    user_id: string,
    data: MicroproofEvidenceModel
  ): Promise<MicroproofEvidenceModel[]> {
    const index = createIndexProofDateUserId(
      proof_date,
      user_id
    );

    const values = MicroproofEvidenceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete microproof_evidence by ProofDateUserId index
   */
  async deleteMicroproofEvidenceByProofDateUserId(
    proof_date: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexProofDateUserId(
      proof_date,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to MicroproofEvidenceModel data array
   */
  private resultToData(values: Data[]): MicroproofEvidenceModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return MicroproofEvidenceModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as MicroproofEvidenceModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized MicroproofEvidenceModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is MicroproofEvidenceModel => item !== null);
  }
}

/**
 * Convert MicroproofEvidenceModel data to Value array
 */
function MicroproofEvidenceModelToValues(data: MicroproofEvidenceModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'proof_date', type: DataType.string, defaultValue: '' },
    { key: 'evidence', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof MicroproofEvidenceModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to MicroproofEvidenceModel data
 */
function MicroproofEvidenceModelFromValues(values: Value[]): MicroproofEvidenceModel {
  const data: Partial<MicroproofEvidenceModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'proof_date':
        data.proof_date = ParseValue(value, DataType.string) as string;
        break;
      case 'evidence':
        data.evidence = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as MicroproofEvidenceModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for ProofDate fields
 */
function createIndexProofDate(
  proof_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, proof_date, 'proof_date'),
  ];

  return {
    fields: ['proof_date'],
    values
  };
}
/**
 * Create index for ProofDateUserId fields
 */
function createIndexProofDateUserId(
  proof_date: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, proof_date, 'proof_date'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['proof_date', 'user_id'],
    values
  };
}

export default MicroproofEvidenceORM;