// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: daily_task.
// - Entity ID: 102019b5ce67409781488b70dbb3e8b247d.
// - Entity Version: 102019b5ff7ffb3702a8d716f62d21a3db0.
// - Task ID: 694fdd1627bf6305174669ec.
// - Task Root ID: 694f132f5296c90e87490c67.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for DailyTaskModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface DailyTaskModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  date: string;
  future_narrative_completed: boolean;
  mismatch_audit_completed: boolean;
  microproof_log_completed: boolean;
  body_protocol_completed: boolean;
}

/**
 * ORM class for DailyTask entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class DailyTaskORM {
  private static instance: DailyTaskORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b5ce67409781488b70dbb3e8b247d';
    this.entityName = 'daily_task';
    this.entityVersion = '102019b5ff7ffb3702a8d716f62d21a3db0';
    this.taskId = '694fdd1627bf6305174669ec';
    this.taskRootId = '694f132f5296c90e87490c67';
  }

  /**
   * Get singleton instance of DailyTaskORM
   */
  public static getInstance(): DailyTaskORM {
    if (!DailyTaskORM.instance) {
      DailyTaskORM.instance = new DailyTaskORM();
    }
    
    return DailyTaskORM.instance;
  }

  /**
   * Get daily_task by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getDailyTaskByIDs(ids: string[]): Promise<DailyTaskModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_task by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteDailyTaskByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all DailyTask records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllDailyTask(): Promise<DailyTaskModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new DailyTask record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertDailyTask(data: DailyTaskModel[]): Promise<DailyTaskModel[]> {
    const structured = data.map((item) => CreateData(DailyTaskModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all DailyTask records
   */
  async purgeAllDailyTask(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List DailyTask records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listDailyTask(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[DailyTaskModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get daily_task by Id index
   * This function gets data by index.
   */
  async getDailyTaskById(
    id: string,
  ): Promise<DailyTaskModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_task by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyTaskById(
    id: string,
    data: DailyTaskModel
  ): Promise<DailyTaskModel[]> {
    const index = createIndexId(
      id
    );

    const values = DailyTaskModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_task by Id index
   */
  async deleteDailyTaskById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_task by DataCreator index
   * This function gets data by index.
   */
  async getDailyTaskByDataCreator(
    data_creator: string,
  ): Promise<DailyTaskModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_task by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyTaskByDataCreator(
    data_creator: string,
    data: DailyTaskModel
  ): Promise<DailyTaskModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = DailyTaskModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_task by DataCreator index
   */
  async deleteDailyTaskByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_task by DataUpdater index
   * This function gets data by index.
   */
  async getDailyTaskByDataUpdater(
    data_updater: string,
  ): Promise<DailyTaskModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_task by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyTaskByDataUpdater(
    data_updater: string,
    data: DailyTaskModel
  ): Promise<DailyTaskModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = DailyTaskModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_task by DataUpdater index
   */
  async deleteDailyTaskByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_task by UserId index
   * This function gets data by index.
   */
  async getDailyTaskByUserId(
    user_id: string,
  ): Promise<DailyTaskModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_task by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyTaskByUserId(
    user_id: string,
    data: DailyTaskModel
  ): Promise<DailyTaskModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = DailyTaskModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_task by UserId index
   */
  async deleteDailyTaskByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_task by DateUserId index
   * This function gets data by index.
   */
  async getDailyTaskByDateUserId(
    date: string,
    user_id: string,
  ): Promise<DailyTaskModel[]> {
    const index = createIndexDateUserId(
      date,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_task by DateUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyTaskByDateUserId(
    date: string,
    user_id: string,
    data: DailyTaskModel
  ): Promise<DailyTaskModel[]> {
    const index = createIndexDateUserId(
      date,
      user_id
    );

    const values = DailyTaskModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_task by DateUserId index
   */
  async deleteDailyTaskByDateUserId(
    date: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexDateUserId(
      date,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_task by Date index
   * This function gets data by index.
   */
  async getDailyTaskByDate(
    date: string,
  ): Promise<DailyTaskModel[]> {
    const index = createIndexDate(
      date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_task by Date index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyTaskByDate(
    date: string,
    data: DailyTaskModel
  ): Promise<DailyTaskModel[]> {
    const index = createIndexDate(
      date
    );

    const values = DailyTaskModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_task by Date index
   */
  async deleteDailyTaskByDate(
    date: string
  ): Promise<void> {
    const index = createIndexDate(
      date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to DailyTaskModel data array
   */
  private resultToData(values: Data[]): DailyTaskModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return DailyTaskModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as DailyTaskModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized DailyTaskModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is DailyTaskModel => item !== null);
  }
}

/**
 * Convert DailyTaskModel data to Value array
 */
function DailyTaskModelToValues(data: DailyTaskModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'date', type: DataType.string, defaultValue: '' },
    { key: 'future_narrative_completed', type: DataType.boolean, defaultValue: false },
    { key: 'mismatch_audit_completed', type: DataType.boolean, defaultValue: false },
    { key: 'microproof_log_completed', type: DataType.boolean, defaultValue: false },
    { key: 'body_protocol_completed', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof DailyTaskModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to DailyTaskModel data
 */
function DailyTaskModelFromValues(values: Value[]): DailyTaskModel {
  const data: Partial<DailyTaskModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'date':
        data.date = ParseValue(value, DataType.string) as string;
        break;
      case 'future_narrative_completed':
        data.future_narrative_completed = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'mismatch_audit_completed':
        data.mismatch_audit_completed = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'microproof_log_completed':
        data.microproof_log_completed = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'body_protocol_completed':
        data.body_protocol_completed = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as DailyTaskModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DateUserId fields
 */
function createIndexDateUserId(
  date: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, date, 'date'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['date', 'user_id'],
    values
  };
}
/**
 * Create index for Date fields
 */
function createIndexDate(
  date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, date, 'date'),
  ];

  return {
    fields: ['date'],
    values
  };
}

export default DailyTaskORM;