// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: program_progress.
// - Entity ID: 102019b5ce674097ab38805780f8f90ce4e.
// - Entity Version: 102019b5ff7ffb3702a8d716f62d21a3db0.
// - Task ID: 694fdd1627bf6305174669ec.
// - Task Root ID: 694f132f5296c90e87490c67.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for ProgramProgressModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ProgramProgressModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  current_week: number;
  current_phase: number;
  phase_start_date: string;
  phase_end_date: string;
}

/**
 * ORM class for ProgramProgress entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ProgramProgressORM {
  private static instance: ProgramProgressORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b5ce674097ab38805780f8f90ce4e';
    this.entityName = 'program_progress';
    this.entityVersion = '102019b5ff7ffb3702a8d716f62d21a3db0';
    this.taskId = '694fdd1627bf6305174669ec';
    this.taskRootId = '694f132f5296c90e87490c67';
  }

  /**
   * Get singleton instance of ProgramProgressORM
   */
  public static getInstance(): ProgramProgressORM {
    if (!ProgramProgressORM.instance) {
      ProgramProgressORM.instance = new ProgramProgressORM();
    }
    
    return ProgramProgressORM.instance;
  }

  /**
   * Get program_progress by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getProgramProgressByIDs(ids: string[]): Promise<ProgramProgressModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete program_progress by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteProgramProgressByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all ProgramProgress records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllProgramProgress(): Promise<ProgramProgressModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ProgramProgress record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertProgramProgress(data: ProgramProgressModel[]): Promise<ProgramProgressModel[]> {
    const structured = data.map((item) => CreateData(ProgramProgressModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ProgramProgress records
   */
  async purgeAllProgramProgress(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ProgramProgress records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listProgramProgress(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ProgramProgressModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get program_progress by Id index
   * This function gets data by index.
   */
  async getProgramProgressById(
    id: string,
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) program_progress by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgramProgressById(
    id: string,
    data: ProgramProgressModel
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexId(
      id
    );

    const values = ProgramProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete program_progress by Id index
   */
  async deleteProgramProgressById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get program_progress by DataCreator index
   * This function gets data by index.
   */
  async getProgramProgressByDataCreator(
    data_creator: string,
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) program_progress by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgramProgressByDataCreator(
    data_creator: string,
    data: ProgramProgressModel
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ProgramProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete program_progress by DataCreator index
   */
  async deleteProgramProgressByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get program_progress by DataUpdater index
   * This function gets data by index.
   */
  async getProgramProgressByDataUpdater(
    data_updater: string,
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) program_progress by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgramProgressByDataUpdater(
    data_updater: string,
    data: ProgramProgressModel
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ProgramProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete program_progress by DataUpdater index
   */
  async deleteProgramProgressByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get program_progress by UserId index
   * This function gets data by index.
   */
  async getProgramProgressByUserId(
    user_id: string,
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) program_progress by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgramProgressByUserId(
    user_id: string,
    data: ProgramProgressModel
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = ProgramProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete program_progress by UserId index
   */
  async deleteProgramProgressByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get program_progress by CurrentWeek index
   * This function gets data by index.
   */
  async getProgramProgressByCurrentWeek(
    current_week: number,
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexCurrentWeek(
      current_week
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) program_progress by CurrentWeek index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgramProgressByCurrentWeek(
    current_week: number,
    data: ProgramProgressModel
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexCurrentWeek(
      current_week
    );

    const values = ProgramProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete program_progress by CurrentWeek index
   */
  async deleteProgramProgressByCurrentWeek(
    current_week: number
  ): Promise<void> {
    const index = createIndexCurrentWeek(
      current_week
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get program_progress by CurrentPhase index
   * This function gets data by index.
   */
  async getProgramProgressByCurrentPhase(
    current_phase: number,
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexCurrentPhase(
      current_phase
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) program_progress by CurrentPhase index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgramProgressByCurrentPhase(
    current_phase: number,
    data: ProgramProgressModel
  ): Promise<ProgramProgressModel[]> {
    const index = createIndexCurrentPhase(
      current_phase
    );

    const values = ProgramProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete program_progress by CurrentPhase index
   */
  async deleteProgramProgressByCurrentPhase(
    current_phase: number
  ): Promise<void> {
    const index = createIndexCurrentPhase(
      current_phase
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ProgramProgressModel data array
   */
  private resultToData(values: Data[]): ProgramProgressModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ProgramProgressModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ProgramProgressModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ProgramProgressModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ProgramProgressModel => item !== null);
  }
}

/**
 * Convert ProgramProgressModel data to Value array
 */
function ProgramProgressModelToValues(data: ProgramProgressModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'current_week', type: DataType.number, defaultValue: 0 },
    { key: 'current_phase', type: DataType.number, defaultValue: 0 },
    { key: 'phase_start_date', type: DataType.string, defaultValue: '' },
    { key: 'phase_end_date', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ProgramProgressModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ProgramProgressModel data
 */
function ProgramProgressModelFromValues(values: Value[]): ProgramProgressModel {
  const data: Partial<ProgramProgressModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'current_week':
        data.current_week = ParseValue(value, DataType.number) as number;
        break;
      case 'current_phase':
        data.current_phase = ParseValue(value, DataType.number) as number;
        break;
      case 'phase_start_date':
        data.phase_start_date = ParseValue(value, DataType.string) as string;
        break;
      case 'phase_end_date':
        data.phase_end_date = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ProgramProgressModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for CurrentWeek fields
 */
function createIndexCurrentWeek(
  current_week: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, current_week, 'current_week'),
  ];

  return {
    fields: ['current_week'],
    values
  };
}
/**
 * Create index for CurrentPhase fields
 */
function createIndexCurrentPhase(
  current_phase: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, current_phase, 'current_phase'),
  ];

  return {
    fields: ['current_phase'],
    values
  };
}

export default ProgramProgressORM;