// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: weekly_ceo_review.
// - Entity ID: 102019b5ce67409754c9835d4e1dbb119ef.
// - Entity Version: 102019b5ff7ffb3702a8d716f62d21a3db0.
// - Task ID: 694fdd1627bf6305174669ec.
// - Task Root ID: 694f132f5296c90e87490c67.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for WeeklyCeoReviewModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface WeeklyCeoReviewModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  week_number: number;
  identity_reinforcement: string;
  old_identity_resurfacing: string;
  system_tweaks: string;
  completed_date: string;
}

/**
 * ORM class for WeeklyCeoReview entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class WeeklyCeoReviewORM {
  private static instance: WeeklyCeoReviewORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b5ce67409754c9835d4e1dbb119ef';
    this.entityName = 'weekly_ceo_review';
    this.entityVersion = '102019b5ff7ffb3702a8d716f62d21a3db0';
    this.taskId = '694fdd1627bf6305174669ec';
    this.taskRootId = '694f132f5296c90e87490c67';
  }

  /**
   * Get singleton instance of WeeklyCeoReviewORM
   */
  public static getInstance(): WeeklyCeoReviewORM {
    if (!WeeklyCeoReviewORM.instance) {
      WeeklyCeoReviewORM.instance = new WeeklyCeoReviewORM();
    }
    
    return WeeklyCeoReviewORM.instance;
  }

  /**
   * Get weekly_ceo_review by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getWeeklyCeoReviewByIDs(ids: string[]): Promise<WeeklyCeoReviewModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete weekly_ceo_review by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteWeeklyCeoReviewByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all WeeklyCeoReview records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllWeeklyCeoReview(): Promise<WeeklyCeoReviewModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new WeeklyCeoReview record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertWeeklyCeoReview(data: WeeklyCeoReviewModel[]): Promise<WeeklyCeoReviewModel[]> {
    const structured = data.map((item) => CreateData(WeeklyCeoReviewModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all WeeklyCeoReview records
   */
  async purgeAllWeeklyCeoReview(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List WeeklyCeoReview records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listWeeklyCeoReview(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[WeeklyCeoReviewModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get weekly_ceo_review by Id index
   * This function gets data by index.
   */
  async getWeeklyCeoReviewById(
    id: string,
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) weekly_ceo_review by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWeeklyCeoReviewById(
    id: string,
    data: WeeklyCeoReviewModel
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexId(
      id
    );

    const values = WeeklyCeoReviewModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete weekly_ceo_review by Id index
   */
  async deleteWeeklyCeoReviewById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get weekly_ceo_review by DataCreator index
   * This function gets data by index.
   */
  async getWeeklyCeoReviewByDataCreator(
    data_creator: string,
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) weekly_ceo_review by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWeeklyCeoReviewByDataCreator(
    data_creator: string,
    data: WeeklyCeoReviewModel
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = WeeklyCeoReviewModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete weekly_ceo_review by DataCreator index
   */
  async deleteWeeklyCeoReviewByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get weekly_ceo_review by DataUpdater index
   * This function gets data by index.
   */
  async getWeeklyCeoReviewByDataUpdater(
    data_updater: string,
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) weekly_ceo_review by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWeeklyCeoReviewByDataUpdater(
    data_updater: string,
    data: WeeklyCeoReviewModel
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = WeeklyCeoReviewModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete weekly_ceo_review by DataUpdater index
   */
  async deleteWeeklyCeoReviewByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get weekly_ceo_review by UserId index
   * This function gets data by index.
   */
  async getWeeklyCeoReviewByUserId(
    user_id: string,
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) weekly_ceo_review by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWeeklyCeoReviewByUserId(
    user_id: string,
    data: WeeklyCeoReviewModel
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = WeeklyCeoReviewModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete weekly_ceo_review by UserId index
   */
  async deleteWeeklyCeoReviewByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get weekly_ceo_review by WeekNumber index
   * This function gets data by index.
   */
  async getWeeklyCeoReviewByWeekNumber(
    week_number: number,
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexWeekNumber(
      week_number
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) weekly_ceo_review by WeekNumber index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWeeklyCeoReviewByWeekNumber(
    week_number: number,
    data: WeeklyCeoReviewModel
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexWeekNumber(
      week_number
    );

    const values = WeeklyCeoReviewModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete weekly_ceo_review by WeekNumber index
   */
  async deleteWeeklyCeoReviewByWeekNumber(
    week_number: number
  ): Promise<void> {
    const index = createIndexWeekNumber(
      week_number
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get weekly_ceo_review by UserIdWeekNumber index
   * This function gets data by index.
   */
  async getWeeklyCeoReviewByUserIdWeekNumber(
    user_id: string,
    week_number: number,
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexUserIdWeekNumber(
      user_id,
      week_number
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) weekly_ceo_review by UserIdWeekNumber index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWeeklyCeoReviewByUserIdWeekNumber(
    user_id: string,
    week_number: number,
    data: WeeklyCeoReviewModel
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexUserIdWeekNumber(
      user_id,
      week_number
    );

    const values = WeeklyCeoReviewModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete weekly_ceo_review by UserIdWeekNumber index
   */
  async deleteWeeklyCeoReviewByUserIdWeekNumber(
    user_id: string,
    week_number: number
  ): Promise<void> {
    const index = createIndexUserIdWeekNumber(
      user_id,
      week_number
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get weekly_ceo_review by CompletedDate index
   * This function gets data by index.
   */
  async getWeeklyCeoReviewByCompletedDate(
    completed_date: string,
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexCompletedDate(
      completed_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) weekly_ceo_review by CompletedDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWeeklyCeoReviewByCompletedDate(
    completed_date: string,
    data: WeeklyCeoReviewModel
  ): Promise<WeeklyCeoReviewModel[]> {
    const index = createIndexCompletedDate(
      completed_date
    );

    const values = WeeklyCeoReviewModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete weekly_ceo_review by CompletedDate index
   */
  async deleteWeeklyCeoReviewByCompletedDate(
    completed_date: string
  ): Promise<void> {
    const index = createIndexCompletedDate(
      completed_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to WeeklyCeoReviewModel data array
   */
  private resultToData(values: Data[]): WeeklyCeoReviewModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return WeeklyCeoReviewModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as WeeklyCeoReviewModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized WeeklyCeoReviewModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is WeeklyCeoReviewModel => item !== null);
  }
}

/**
 * Convert WeeklyCeoReviewModel data to Value array
 */
function WeeklyCeoReviewModelToValues(data: WeeklyCeoReviewModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'week_number', type: DataType.number, defaultValue: 0 },
    { key: 'identity_reinforcement', type: DataType.string, defaultValue: '' },
    { key: 'old_identity_resurfacing', type: DataType.string, defaultValue: '' },
    { key: 'system_tweaks', type: DataType.string, defaultValue: '' },
    { key: 'completed_date', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof WeeklyCeoReviewModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to WeeklyCeoReviewModel data
 */
function WeeklyCeoReviewModelFromValues(values: Value[]): WeeklyCeoReviewModel {
  const data: Partial<WeeklyCeoReviewModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'week_number':
        data.week_number = ParseValue(value, DataType.number) as number;
        break;
      case 'identity_reinforcement':
        data.identity_reinforcement = ParseValue(value, DataType.string) as string;
        break;
      case 'old_identity_resurfacing':
        data.old_identity_resurfacing = ParseValue(value, DataType.string) as string;
        break;
      case 'system_tweaks':
        data.system_tweaks = ParseValue(value, DataType.string) as string;
        break;
      case 'completed_date':
        data.completed_date = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as WeeklyCeoReviewModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for WeekNumber fields
 */
function createIndexWeekNumber(
  week_number: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, week_number, 'week_number'),
  ];

  return {
    fields: ['week_number'],
    values
  };
}
/**
 * Create index for UserIdWeekNumber fields
 */
function createIndexUserIdWeekNumber(
  user_id: string,
  week_number: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
    CreateValue(DataType.number, week_number, 'week_number'),
  ];

  return {
    fields: ['user_id', 'week_number'],
    values
  };
}
/**
 * Create index for CompletedDate fields
 */
function createIndexCompletedDate(
  completed_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, completed_date, 'completed_date'),
  ];

  return {
    fields: ['completed_date'],
    values
  };
}

export default WeeklyCeoReviewORM;