// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: journal_entry.
// - Entity ID: 102019b5ce6740971779f1231a32065645e.
// - Entity Version: 102019b5ff7ffb3702a8d716f62d21a3db0.
// - Task ID: 694fdd1627bf6305174669ec.
// - Task Root ID: 694f132f5296c90e87490c67.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for JournalEntryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface JournalEntryModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  entry_date: string;
  narrative: string;
  character_count: number;
}

/**
 * ORM class for JournalEntry entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class JournalEntryORM {
  private static instance: JournalEntryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b5ce6740971779f1231a32065645e';
    this.entityName = 'journal_entry';
    this.entityVersion = '102019b5ff7ffb3702a8d716f62d21a3db0';
    this.taskId = '694fdd1627bf6305174669ec';
    this.taskRootId = '694f132f5296c90e87490c67';
  }

  /**
   * Get singleton instance of JournalEntryORM
   */
  public static getInstance(): JournalEntryORM {
    if (!JournalEntryORM.instance) {
      JournalEntryORM.instance = new JournalEntryORM();
    }
    
    return JournalEntryORM.instance;
  }

  /**
   * Get journal_entry by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getJournalEntryByIDs(ids: string[]): Promise<JournalEntryModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete journal_entry by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteJournalEntryByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all JournalEntry records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllJournalEntry(): Promise<JournalEntryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new JournalEntry record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertJournalEntry(data: JournalEntryModel[]): Promise<JournalEntryModel[]> {
    const structured = data.map((item) => CreateData(JournalEntryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all JournalEntry records
   */
  async purgeAllJournalEntry(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List JournalEntry records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listJournalEntry(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[JournalEntryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get journal_entry by Id index
   * This function gets data by index.
   */
  async getJournalEntryById(
    id: string,
  ): Promise<JournalEntryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) journal_entry by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJournalEntryById(
    id: string,
    data: JournalEntryModel
  ): Promise<JournalEntryModel[]> {
    const index = createIndexId(
      id
    );

    const values = JournalEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete journal_entry by Id index
   */
  async deleteJournalEntryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get journal_entry by DataCreator index
   * This function gets data by index.
   */
  async getJournalEntryByDataCreator(
    data_creator: string,
  ): Promise<JournalEntryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) journal_entry by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJournalEntryByDataCreator(
    data_creator: string,
    data: JournalEntryModel
  ): Promise<JournalEntryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = JournalEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete journal_entry by DataCreator index
   */
  async deleteJournalEntryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get journal_entry by DataUpdater index
   * This function gets data by index.
   */
  async getJournalEntryByDataUpdater(
    data_updater: string,
  ): Promise<JournalEntryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) journal_entry by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJournalEntryByDataUpdater(
    data_updater: string,
    data: JournalEntryModel
  ): Promise<JournalEntryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = JournalEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete journal_entry by DataUpdater index
   */
  async deleteJournalEntryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get journal_entry by UserId index
   * This function gets data by index.
   */
  async getJournalEntryByUserId(
    user_id: string,
  ): Promise<JournalEntryModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) journal_entry by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJournalEntryByUserId(
    user_id: string,
    data: JournalEntryModel
  ): Promise<JournalEntryModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = JournalEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete journal_entry by UserId index
   */
  async deleteJournalEntryByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get journal_entry by EntryDate index
   * This function gets data by index.
   */
  async getJournalEntryByEntryDate(
    entry_date: string,
  ): Promise<JournalEntryModel[]> {
    const index = createIndexEntryDate(
      entry_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) journal_entry by EntryDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJournalEntryByEntryDate(
    entry_date: string,
    data: JournalEntryModel
  ): Promise<JournalEntryModel[]> {
    const index = createIndexEntryDate(
      entry_date
    );

    const values = JournalEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete journal_entry by EntryDate index
   */
  async deleteJournalEntryByEntryDate(
    entry_date: string
  ): Promise<void> {
    const index = createIndexEntryDate(
      entry_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get journal_entry by EntryDateUserId index
   * This function gets data by index.
   */
  async getJournalEntryByEntryDateUserId(
    entry_date: string,
    user_id: string,
  ): Promise<JournalEntryModel[]> {
    const index = createIndexEntryDateUserId(
      entry_date,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) journal_entry by EntryDateUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJournalEntryByEntryDateUserId(
    entry_date: string,
    user_id: string,
    data: JournalEntryModel
  ): Promise<JournalEntryModel[]> {
    const index = createIndexEntryDateUserId(
      entry_date,
      user_id
    );

    const values = JournalEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete journal_entry by EntryDateUserId index
   */
  async deleteJournalEntryByEntryDateUserId(
    entry_date: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexEntryDateUserId(
      entry_date,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to JournalEntryModel data array
   */
  private resultToData(values: Data[]): JournalEntryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return JournalEntryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as JournalEntryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized JournalEntryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is JournalEntryModel => item !== null);
  }
}

/**
 * Convert JournalEntryModel data to Value array
 */
function JournalEntryModelToValues(data: JournalEntryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'entry_date', type: DataType.string, defaultValue: '' },
    { key: 'narrative', type: DataType.string, defaultValue: '' },
    { key: 'character_count', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof JournalEntryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to JournalEntryModel data
 */
function JournalEntryModelFromValues(values: Value[]): JournalEntryModel {
  const data: Partial<JournalEntryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'entry_date':
        data.entry_date = ParseValue(value, DataType.string) as string;
        break;
      case 'narrative':
        data.narrative = ParseValue(value, DataType.string) as string;
        break;
      case 'character_count':
        data.character_count = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as JournalEntryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for EntryDate fields
 */
function createIndexEntryDate(
  entry_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, entry_date, 'entry_date'),
  ];

  return {
    fields: ['entry_date'],
    values
  };
}
/**
 * Create index for EntryDateUserId fields
 */
function createIndexEntryDateUserId(
  entry_date: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, entry_date, 'entry_date'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['entry_date', 'user_id'],
    values
  };
}

export default JournalEntryORM;