// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PostV1AiZWwyutGgvEgWwzSaChatCompletionsData, PostV1AiZWwyutGgvEgWwzSaChatCompletionsErrors, PostV1AiZWwyutGgvEgWwzSaChatCompletionsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Chat completion with image recognition
 *
 * Sends messages including images for analysis and receives JSON formatted responses
 */
export const postV1AiZWwyutGgvEgWwzSaChatCompletions = <ThrowOnError extends boolean = false>(options: Options<PostV1AiZWwyutGgvEgWwzSaChatCompletionsData, ThrowOnError>) => (options.client ?? client).post<PostV1AiZWwyutGgvEgWwzSaChatCompletionsResponses, PostV1AiZWwyutGgvEgWwzSaChatCompletionsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai/zWwyutGgvEGWwzSa/chat/completions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
