import { platformRequest } from '@/sdk/core/request';
// This file is auto-generated by @hey-api/openapi-ts

import { type ClientOptions, type Config, createClient, createConfig } from './client';
import type { ClientOptions as ClientOptions2 } from './types.gen';

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends ClientOptions = ClientOptions2> = (override?: Config<ClientOptions & T>) => Config<Required<ClientOptions> & T>;

export const client = createClient(createConfig<ClientOptions2>({fetch: async function patchedFetch(init: any, ...args: any[]) {
  // don't edit
  let url = new URL(init.url);
  let newInit = new Request(url, init);
  let headers = newInit.headers;
  headers.set("X-CREAO-API-NAME", "OpenAIGPTChat");
  headers.set("X-CREAO-API-ID", "688a0b64dc79a2533460892c");
  headers.set("X-CREAO-API-PATH", url.pathname.slice(16));
  return await platformRequest(newInit, ...args);
},
baseUrl: "https://api-production.creao.ai/execute-apis/v2" }));
